# 基础配置
app:
  name: "rag-knowledge-base"
  version: "0.1.0"

# 数据配置
data:
  raw_file: "data/raw/knowledge_base.xlsx"
  processed_dir: "data/processed"
  vector_store_path: "data/vector_db/faiss_index"
  documents_filename: "documents.db" # <--- 新增: 指定SQLite数据库文件名

# 嵌入模型配置
embedding:
  # 使用BGE中文模型
  model_path: "models/bge-small-zh-v1.5"
  dimension: 512  # bge-small-zh-v1.5 向量维度为512
  batch_size: 32 # 基础批处理大小
  normalize_embeddings: true  # BGE模型推荐设置归一化
  use_gpu: true  # 在Windows上构建索引时使用GPU

# 服务器环境配置(低内存模式)
server:
  low_memory_mode: true  # 为低内存服务器优化
  load_model_on_demand: true  # 只在需要时加载模型
  enable_model_unloading: false  # 不允许卸载模型

# 中文文本处理配置
preprocessing:
  chunk_size: 256 # 文本块大小
  chunk_overlap: 50
  # 可以根据文本特点调整这些参数

# FAISS配置
faiss:
  index_type: "IndexIVFPQ"    # <--- 修改: 使用 PQ 压缩
  use_gpu: false              # 服务器通常是CPU
  nlist: 256                  # <--- 修改/新增: IVF 聚类数 (根据数据量调整)
  pq_m: 64                    # <--- 新增: PQ 子向量数 (512/64=8)
  pq_nbits: 8                 # <--- 新增: 每个子向量的比特数
  nprobe: 10                  # 查询时探测的单元数
  use_mmap: false             # <--- 修改: 禁用内存映射

# 内存管理配置
memory:
  lazy_loading: true          # 启用文档惰性加载
  unload_after_query: true    # 查询后卸载文档数据缓存
  documents_batch_size: 1000  # 批量加载文档数量

# API服务配置
api:
  host: localhost
  port: 8000
  workers: 1  # 减少工作进程数量以降低内存占用
  root_path: "/rag"  # 适应Nginx反向代理的路径前缀
